### ISSUE TITLE
[Feature request] Include transpiled/bundled source

### ISSUE THREAD

**Issue by kceb** [infuse-us/redux-responder#1]
When I run a jest test for a local project, it is complaining about the import statement here: https://github.com/infuse-us/redux-responder/blob/master/src/index.js#L1

My guess is because the import statement is es6 syntax and jest only understands js. I realize that I should probably be stubbing/mocking external libraries, so maybe this feature/enhancement isn't really needed

I think including a /lib folder with a transpiled/bundled source (via babel) may solve the issue.

**Comment by kceb** [comment]
PR: https://github.com/infuse-us/redux-responder/pull/2/files

**Comment by jaschaephraim** [comment]
Resolved by #2
